import{a as x,S as L,i as d}from"./assets/vendor-c493984e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&c(u)}).observe(document,{childList:!0,subtree:!0});function a(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(o){if(o.ep)return;o.ep=!0;const r=a(o);fetch(o.href,r)}})();async function m(t,e){return(await x.get("https://pixabay.com/api/",{params:{key:"44631017-28d3930dbc3d7d0d9679d8f71",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}function p(t){return t.map(e=>`<li class="element-gallery">
      <a class="gallery-link" href="${e.largeImageURL}">
    <img class="img-gallery" src="${e.webformatURL}" alt="${e.tags}">
    <ul class="list-info">
    <li class="item-info"><h3 class="title-text">Likes</h3>
    <p class="text">${e.likes}</p></li>
    <li class="item-info"><h3 class="title-text">Views</h3>
    <p class="text">${e.views}</p></li>
    <li class="item-info"><h3 class="title-text">Comments</h3>
    <p class="text">${e.comments}</p></li>
    <li class="item-info"><h3 class="title-text">Downloads</h3>
    <p class="text">${e.downloads}</p></li>
   </ul>
  </li>`).join("")}const y=new L(".gallery a",{captionsData:"alt",captionDelay:325});function f(){const t=document.querySelector(".loader");t.style.display="block"}function s(){const t=document.querySelector(".loader");t.style.display="none"}function i(){const t=document.querySelector(".loadButton");t.style.display="none"}function g(){const t=document.querySelector(".loadButton");t.style.display="block"}const S=document.querySelector(".form"),q=document.querySelector('input[name = "value"]'),h=document.querySelector(".gallery"),B=document.querySelector(".loadButton");let n,l,C,b=0,v=15;s();i();S.addEventListener("submit",k);async function k(t){if(f(),t.preventDefault(),i(),h.innerHTML="",l=q.value.trim(),!l){s(),d.error({message:"Please enter something",position:"bottomCenter",maxWidth:350,backgroundColor:"red",messageColor:"white"});return}n=1,f();try{const e=await m(l);b=Math.ceil(e.totalHits/v);const a=await m(l,n);if(a.hits.length===0){s(),d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomCenter",maxWidth:350,backgroundColor:"red",messageColor:"white"});return}const c=p(a.hits);h.innerHTML=c}catch{}y.refresh(),s(),g(),w()}B.addEventListener("click",P);async function P(){f(),i(),n+=1;try{const t=await m(l,n),e=p(t.hits);h.insertAdjacentHTML("beforeend",e),y.refresh()}catch(t){console.log(t)}s(),g(),$(),w()}function $(){const e=document.querySelector("li").getBoundingClientRect().height;window.scrollBy({top:e*3,behavior:"smooth"})}function w(){n===C&&(i(),s(),d.error({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",maxWidth:350,backgroundColor:"red",messageColor:"white"})),n>=b&&i()}
//# sourceMappingURL=commonHelpers.js.map
