import{a as w,S as x,i as u}from"./assets/vendor-c493984e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))f(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&f(c)}).observe(document,{childList:!0,subtree:!0});function a(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function f(o){if(o.ep)return;o.ep=!0;const r=a(o);fetch(o.href,r)}})();async function h(t,e){return(await w.get("https://pixabay.com/api/",{params:{key:"44631017-28d3930dbc3d7d0d9679d8f71",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}function p(t){return t.map(e=>`<li class="element-gallery">
      <a class="gallery-link" href="${e.largeImageURL}">
    <img class="img-gallery" src="${e.webformatURL}" alt="${e.tags}">
    <ul class="list-info">
    <li class="item-info"><h3 class="title-text">Likes</h3>
    <p class="text">${e.likes}</p></li>
    <li class="item-info"><h3 class="title-text">Views</h3>
    <p class="text">${e.views}</p></li>
    <li class="item-info"><h3 class="title-text">Comments</h3>
    <p class="text">${e.comments}</p></li>
    <li class="item-info"><h3 class="title-text">Downloads</h3>
    <p class="text">${e.downloads}</p></li>
   </ul>
  </li>`).join("")}const y=new x(".gallery a",{captionsData:"alt",captionDelay:325});function d(){const t=document.querySelector(".loader");t.style.display="block"}function s(){const t=document.querySelector(".loader");t.style.display="none"}function i(){const t=document.querySelector(".loadButton");t.style.display="none"}function g(){const t=document.querySelector(".loadButton");t.style.display="block"}const L=document.querySelector(".form"),S=document.querySelector('input[name = "value"]'),m=document.querySelector(".gallery"),q=document.querySelector(".loadButton");let n,l,B=3;s();i();L.addEventListener("submit",C);async function C(t){if(d(),t.preventDefault(),i(),m.innerHTML="",l=S.value,!!l){n=1,d();try{const e=await h(l,n);if(e.hits.length===0){s(),u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomCenter",maxWidth:350,backgroundColor:"red",messageColor:"white"});return}e.totalHits>0&&(s(),u.info({message:"Пошук успішний, але я обмежив кількість сторінок, щоб Ви дійшли до останньої",position:"center",maxWidth:350,backgroundColor:"green",messageColor:"white"}));const a=p(e.hits);m.innerHTML=a}catch(e){showMessage(e)}y.refresh(),s(),g(),b()}}q.addEventListener("click",v);async function v(){d(),i(),n+=1;try{const t=await h(l,n),e=p(t.hits);m.insertAdjacentHTML("beforeend",e)}catch(t){console.log(t)}y.refresh(),s(),g(),k(),b()}function k(){const e=document.querySelector("li").getBoundingClientRect().height;window.scrollBy({top:e*3,behavior:"smooth"})}function b(){n===B&&(i(),s(),u.error({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",maxWidth:350,backgroundColor:"red",messageColor:"white"}))}
//# sourceMappingURL=commonHelpers.js.map
